server:
  port: 8080
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://localhost:5432/edms
    username: postgres
    password: admin
  flyway:
    locations: classpath:migrations
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
edms:
  aes:
    algorithm: AES/CBC/PKCS5Padding
    key: test
    salt: test
  minio:
    endpoint: http://45.95.202.170:9000
    accessKey: minioadmin
    secretKey: minioadmin
